=== ElbErt-Roi/Web-Technology/Lab/xml dtd $ schema/6.School.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="University">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="School" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SchoolID" type="xs:string"/>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Location" type="xs:string"/>
                            <xs:element name="Staff" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="StaffID" type="xs:string"/>
                                        <xs:element name="Name" type="xs:string"/>
                                        <xs:element name="Title" type="xs:string" minOccurs="0"/>
                                        <xs:element name="Category">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="academic"/>
                                                    <xs:enumeration value="general"/>
                                                    <xs:enumeration value="technical"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Addresses" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Street" type="xs:string"/>
                                                    <xs:element name="Suburb" type="xs:string"/>
                                                    <xs:element name="Postcode" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Subjects" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="SubjectCode" type="xs:string"/>
                                        <xs:element name="Name" type="xs:string"/>
                                        <xs:element name="Description" type="xs:string"/>
                                        <xs:element name="Capacity">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="6"/>
                                                    <xs:maxInclusive value="400"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="TaughtBy" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ElbErt-Roi/Web-Technology/Lab/xml dtd $ schema/6.School.xml
<?xml version="1.0" encoding="UTF-8"?>
<University xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Lenovo/Desktop/web%20Lab/Lab/xml%20dtd%20$%20schema/6.School.xsd">
    <School>
        <SchoolID>1</SchoolID>
        <Name>Dev School</Name>
        <Location>Kathmandu</Location>
        <Staff>
            <StaffID>100</StaffID>
            <Name>Dr. Hari Thapa</Name>
            <Title>Professor</Title>
            <Category>academic</Category>
            <Addresses>
                <Street>123 Main Street</Street>
                <Suburb>Lalitpur</Suburb>
                <Postcode>4567</Postcode>
            </Addresses>
            <Addresses>
            
                <Street>Rainbow Secondary Street</Street>
                <Suburb>Bhaktapur</Suburb>
                <Postcode>44800</Postcode>
            </Addresses>
        </Staff>
        <Staff>
            <StaffID>102</StaffID>
            <Name>Sita Sharma</Name>
            <Title></Title>
            <Category>general</Category>
            <Addresses>
                <Street>7 Street</Street>
                <Suburb>Kathmandu</Suburb>
                <Postcode>44600</Postcode>
            </Addresses>
        </Staff>
        <Subjects>
            <SubjectCode>ENG101</SubjectCode>
            <Name>Introduction to Engineering</Name>
            <Description>Basics of engineering principles</Description>
            <Capacity>150</Capacity>
            <TaughtBy>101</TaughtBy>
        </Subjects>
        <Subjects>
            <SubjectCode>ENG202</SubjectCode>
            <Name>Advanced Thermodynamics</Name>
            <Description>In-depth study of thermodynamics concepts</Description>
            <Capacity>30</Capacity>
            <TaughtBy>101</TaughtBy>
        </Subjects>
    </School>
</University>
