=== ElbErt-Roi/Web-Technology/P Code/dtd schema xma/q2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="PatientDetails">
<xs:complexType>
<xs:sequence>
<xs:element name="title" type="xs:string"/>
<xs:element name="patient">
<xs:complexType>
<xs:sequence>
<xs:element name="patients" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="name">
<xs:complexType>
<xs:sequence>
<xs:element name="fname" type="xs:string"/>
<xs:element name="mname"  type="xs:string" minOccurs="0"/>
<xs:element name="lname" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="Pnum" type="xs:string"/>
<xs:element name="Dname" type="xs:string"/>
<xs:element name="Disease" type="xs:string" maxOccurs="unbounded"/>
<xs:element name="charge" type="xs:string"/>
<xs:element name="test" type="xs:string" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>

</xs:element>
</xs:schema>

=== ElbErt-Roi/Web-Technology/P Code/dtd schema xma/q2.xml
<?xml version="1.0"?>
<PatientDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="q2.xsd">
<title>Patient list Details</title> 
<patient>
<patients>
<name>
<fname>Raju</fname>
<mname>Bhadur</mname>
<lname>Thapa</lname>
</name>
<Pnum>420</Pnum>
<Dname>Dr.Suresh</Dname>
<Disease>flue</Disease>
<Disease>fever</Disease>
<charge>700</charge>
<test>oii</test>
</patients>
</patient>
 </PatientDetails>
